<option value="">Select Country</option>
<option value="L&#039;Afghanistan">L&#039;Afghanistan</option>
<option value="Iles Aland">Iles Aland</option>
<option value="Albanie">Albanie</option>
<option value="Algérie">Algérie</option>
<option value="Samoa américaines">Samoa américaines</option>
<option value="Andorre">Andorre</option>
<option value="L&#039;Angola">L&#039;Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antarctique">Antarctique</option>
<option value="Antigua-et-Barbuda">Antigua-et-Barbuda</option>
<option value="Argentine">Argentine</option>
<option value="Arménie">Arménie</option>
<option value="Aruba">Aruba</option>
<option value="Australie">Australie</option>
<option value="L&#039;Autriche">L&#039;Autriche</option>
<option value="Azerbaïdjan">Azerbaïdjan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahreïn">Bahreïn</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbade">Barbade</option>
<option value="Biélorussie">Biélorussie</option>
<option value="Belgique">Belgique</option>
<option value="Belize">Belize</option>
<option value="Bénin">Bénin</option>
<option value="Bermudes">Bermudes</option>
<option value="Bhoutan">Bhoutan</option>
<option value="Bolivie">Bolivie</option>
<option value="Bonaire, Saint-Eustache et Saba">Bonaire, Saint-Eustache et Saba</option>
<option value="Bosnie Herzégovine">Bosnie Herzégovine</option>
<option value="Botswana">Botswana</option>
<option value="Île Bouvet">Île Bouvet</option>
<option value="Brésil">Brésil</option>
<option value="Territoire britannique de l&#039;océan Indien">Territoire britannique de l&#039;océan Indien</option>
<option value="Brunei Darussalam">Brunei Darussalam</option>
<option value="Bulgarie">Bulgarie</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodge">Cambodge</option>
<option value="Cameroun">Cameroun</option>
<option value="Canada">Canada</option>
<option value="Cap-Vert">Cap-Vert</option>
<option value="Îles Caïmans">Îles Caïmans</option>
<option value="République centrafricaine">République centrafricaine</option>
<option value="Tchad">Tchad</option>
<option value="Chili">Chili</option>
<option value="Chine">Chine</option>
<option value="L&#039;île de noël">L&#039;île de noël</option>
<option value="Îles Cocos (Keeling)">Îles Cocos (Keeling)</option>
<option value="Colombie">Colombie</option>
<option value="Comores">Comores</option>
<option value="Congo">Congo</option>
<option value="Congo, République démocratique du Congo">Congo, République démocratique du Congo</option>
<option value="les Îles Cook">les Îles Cook</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Côte d&#039;Ivoire">Côte d&#039;Ivoire</option>
<option value="Croatie">Croatie</option>
<option value="Cuba">Cuba</option>
<option value="Curacao">Curacao</option>
<option value="Chypre">Chypre</option>
<option value="République Tchèque">République Tchèque</option>
<option value="Danemark">Danemark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominique">Dominique</option>
<option value="République dominicaine">République dominicaine</option>
<option value="Equateur">Equateur</option>
<option value="Egypte">Egypte</option>
<option value="Le Salvador">Le Salvador</option>
<option value="Guinée Équatoriale">Guinée Équatoriale</option>
<option value="Érythrée">Érythrée</option>
<option value="Estonie">Estonie</option>
<option value="Ethiopie">Ethiopie</option>
<option value="Îles Falkland (Malvinas)">Îles Falkland (Malvinas)</option>
<option value="Îles Féroé">Îles Féroé</option>
<option value="Fidji">Fidji</option>
<option value="Finlande">Finlande</option>
<option value="France">France</option>
<option value="Guyane Française">Guyane Française</option>
<option value="Polynésie française">Polynésie française</option>
<option value="Terres australes françaises">Terres australes françaises</option>
<option value="Gabon">Gabon</option>
<option value="Gambie">Gambie</option>
<option value="Géorgie">Géorgie</option>
<option value="Allemagne">Allemagne</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Grèce">Grèce</option>
<option value="Groenland">Groenland</option>
<option value="Grenade">Grenade</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guernesey">Guernesey</option>
<option value="Guinée">Guinée</option>
<option value="Guinée-Bissau">Guinée-Bissau</option>
<option value="Guyane">Guyane</option>
<option value="Haïti">Haïti</option>
<option value="Îles Heard et McDonald">Îles Heard et McDonald</option>
<option value="Saint-Siège (État de la Cité du Vatican)">Saint-Siège (État de la Cité du Vatican)</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hongrie">Hongrie</option>
<option value="Islande">Islande</option>
<option value="Inde">Inde</option>
<option value="Indonésie">Indonésie</option>
<option value="Iran (République islamique d">Iran (République islamique d</option>
<option value="Irak">Irak</option>
<option value="Irlande">Irlande</option>
<option value="île de Man">île de Man</option>
<option value="Israël">Israël</option>
<option value="Italie">Italie</option>
<option value="Jamaïque">Jamaïque</option>
<option value="Japon">Japon</option>
<option value="Jersey">Jersey</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="République populaire démocratique de Corée">République populaire démocratique de Corée</option>
<option value="Corée, République de">Corée, République de</option>
<option value="Kosovo">Kosovo</option>
<option value="Koweit">Koweit</option>
<option value="Kirghizistan">Kirghizistan</option>
<option value="République démocratique populaire lao">République démocratique populaire lao</option>
<option value="Lettonie">Lettonie</option>
<option value="Liban">Liban</option>
<option value="Lesotho">Lesotho</option>
<option value="Libéria">Libéria</option>
<option value="Jamahiriya arabe libyenne">Jamahiriya arabe libyenne</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lituanie">Lituanie</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macao">Macao</option>
<option value="Macédoine, ancienne République yougoslave de">Macédoine, ancienne République yougoslave de</option>
<option value="Madagascar">Madagascar</option>
<option value="Malawi">Malawi</option>
<option value="Malaisie">Malaisie</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malte">Malte</option>
<option value="Iles Marshall">Iles Marshall</option>
<option value="Martinique">Martinique</option>
<option value="Mauritanie">Mauritanie</option>
<option value="Ile Maurice">Ile Maurice</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexique">Mexique</option>
<option value="Micronésie, États fédérés de">Micronésie, États fédérés de</option>
<option value="Moldova, République de">Moldova, République de</option>
<option value="Monaco">Monaco</option>
<option value="Mongolie">Mongolie</option>
<option value="Monténégro">Monténégro</option>
<option value="Montserrat">Montserrat</option>
<option value="Maroc">Maroc</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Namibie">Namibie</option>
<option value="Nauru">Nauru</option>
<option value="Népal">Népal</option>
<option value="Pays-Bas">Pays-Bas</option>
<option value="Antilles néerlandaises">Antilles néerlandaises</option>
<option value="Nouvelle Calédonie">Nouvelle Calédonie</option>
<option value="Nouvelle-Zélande">Nouvelle-Zélande</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Niue</option>
<option value="l&#039;ile de Norfolk">l&#039;ile de Norfolk</option>
<option value="Îles Mariannes du Nord">Îles Mariannes du Nord</option>
<option value="Norvège">Norvège</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau">Palau</option>
<option value="Territoire palestinien, occupé">Territoire palestinien, occupé</option>
<option value="Panama">Panama</option>
<option value="Papouasie Nouvelle Guinée">Papouasie Nouvelle Guinée</option>
<option value="Paraguay">Paraguay</option>
<option value="Pérou">Pérou</option>
<option value="Philippines">Philippines</option>
<option value="Pitcairn">Pitcairn</option>
<option value="Pologne">Pologne</option>
<option value="Le Portugal">Le Portugal</option>
<option value="Porto Rico">Porto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Réunion">Réunion</option>
<option value="Roumanie">Roumanie</option>
<option value="Fédération Russe">Fédération Russe</option>
<option value="Rwanda">Rwanda</option>
<option value="Saint Barthélemy">Saint Barthélemy</option>
<option value="Sainte-Hélène">Sainte-Hélène</option>
<option value="Saint-Christophe-et-Niévès">Saint-Christophe-et-Niévès</option>
<option value="Sainte-Lucie">Sainte-Lucie</option>
<option value="Saint Martin">Saint Martin</option>
<option value="Saint-Pierre-et-Miquelon">Saint-Pierre-et-Miquelon</option>
<option value="Saint-Vincent-et-les-Grenadines">Saint-Vincent-et-les-Grenadines</option>
<option value="Samoa">Samoa</option>
<option value="Saint Marin">Saint Marin</option>
<option value="Sao Tomé et Principe">Sao Tomé et Principe</option>
<option value="Arabie Saoudite">Arabie Saoudite</option>
<option value="Sénégal">Sénégal</option>
<option value="Serbie">Serbie</option>
<option value="Serbie et Monténégro">Serbie et Monténégro</option>
<option value="les Seychelles">les Seychelles</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapour">Singapour</option>
<option value="St Martin">St Martin</option>
<option value="Slovaquie">Slovaquie</option>
<option value="Slovénie">Slovénie</option>
<option value="Les îles Salomon">Les îles Salomon</option>
<option value="Somalie">Somalie</option>
<option value="Afrique du Sud">Afrique du Sud</option>
<option value="Géorgie du Sud et îles Sandwich du Sud">Géorgie du Sud et îles Sandwich du Sud</option>
<option value="Soudan du sud">Soudan du sud</option>
<option value="Espagne">Espagne</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Soudan">Soudan</option>
<option value="Suriname">Suriname</option>
<option value="Svalbard et Jan Mayen">Svalbard et Jan Mayen</option>
<option value="Swaziland">Swaziland</option>
<option value="Suède">Suède</option>
<option value="la Suisse">la Suisse</option>
<option value="République arabe syrienne">République arabe syrienne</option>
<option value="Taiwan, Province de Chine">Taiwan, Province de Chine</option>
<option value="Tadjikistan">Tadjikistan</option>
<option value="Tanzanie, République-Unie de">Tanzanie, République-Unie de</option>
<option value="Thaïlande">Thaïlande</option>
<option value="Timor-Leste">Timor-Leste</option>
<option value="Aller">Aller</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinité-et-Tobago">Trinité-et-Tobago</option>
<option value="Tunisie">Tunisie</option>
<option value="dinde">dinde</option>
<option value="Turkménistan">Turkménistan</option>
<option value="îles Turques-et-Caïques">îles Turques-et-Caïques</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Ouganda">Ouganda</option>
<option value="Ukraine">Ukraine</option>
<option value="Emirats Arabes Unis">Emirats Arabes Unis</option>
<option value="Royaume-Uni">Royaume-Uni</option>
<option value="États-Unis">États-Unis</option>
<option value="Îles mineures éloignées des États-Unis">Îles mineures éloignées des États-Unis</option>
<option value="Uruguay">Uruguay</option>
<option value="Ouzbékistan">Ouzbékistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Venezuela">Venezuela</option>
<option value="Viet Nam">Viet Nam</option>
<option value="Îles Vierges britanniques">Îles Vierges britanniques</option>
<option value="Îles Vierges américaines, États-Unis">Îles Vierges américaines, États-Unis</option>
<option value="Wallis et Futuna">Wallis et Futuna</option>
<option value="Sahara occidental">Sahara occidental</option>
<option value="Yémen">Yémen</option>
<option value="Zambie">Zambie</option>
<option value="Zimbabwe">Zimbabwe</option>
